### ISSUE TITLE
No pattern specified in google.api.HttpRule

### ISSUE THREAD

**Issue by pgracio** [gengo/grpc-gateway#70] opened 2015-12-09 14:06 UTC
Hi,

I'm starting using grpc-gateway and this is probably a newbie question.

When running this I'm getting the following error. Probably missing something...

```
~/github/grpc-gateway (master)$ protoc -I/usr/local/include -I.  -I$GOPATH/src  -I$GOPATH/src/github.com/gengo/grpc-gateway/third_party/googleapis  --grpc-gateway_out=logtostderr=true:.  examples/examplepb/echo_service.proto
E1209 15:00:22.665743   18512 services.go:107] No pattern specified in google.api.HttpRule: Echo
```

Thanks,
Paulo Grácio

**Comment by mtsgrd** [comment] 2015-12-09 16:51
+1

**Comment by codefx9** [comment] 2015-12-10 00:35
I am facing a similar issue. I also noticed that the problem did not occur on a different computer with "same" setup steps. Here is a contrived example that shows how to reproduce this issue:

First I modified the Makefile to avoid the `google/http` issue (#67):
```
$ cd $GOPATH/src/github.com/gengo/grpc-gateway

$ nano Makefile
examples: $(EXAMPLE_SVCSRCS) $(EXAMPLE_GWSRCS) $(EXAMPLE_DEPSRCS)
	sed -i "s/import _ \"google\/api\"//" ./examples/**/*.pb.go

$ make test
```
Test run successfully. Now I undo all the changes made by `make test`. This reverts the generated files back to their original version.
```
$ git reset HEAD --hard
```
Now, if I run `make test`, I get the following error:
```
$ make test
go build -o bin/protoc-gen-grpc-gateway github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
protoc -I /usr/local/bin//../include -I. -Ithird_party/googleapis --plugin=bin/protoc-gen-grpc-gateway --grpc-gateway_out=logtostderr=true,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor,Mexamples/sub/message.proto=github.com/gengo/grpc-gateway/examples/sub:. examples/examplepb/echo_service.proto examples/examplepb/a_bit_of_everything.proto examples/examplepb/flow_combination.proto
E1210 06:26:49.972372    7693 services.go:107] No pattern specified in google.api.HttpRule: Echo
--grpc-gateway_out: none of pattern specified
make: *** [examples/examplepb/echo_service.pb.gw.go] Error 1
```

If I run `make realclean` (and add the google/http sed rule) and then run `make test`, everything works again. @yugui, can you please help us fix this issue?

**Comment by yugui** [comment] 2015-12-10 00:53
I'm trying to investigate the issue.

There are some quick updates:
* I am not sure why `make test` works fine. But protoc-gen-grpc-gateway fails to load message descriptor correctly.  When it loads your message descriptor, the descriptor actually lacks http path mapping even though you specified it in .proto file.
* Another possibly related thing is that `proto.MarshalText` and `proto.UnmarshalText` don't roundtrip for oneof fields.

**Comment by yugui** [comment] 2015-12-10 01:16
The root cause was that generated `third_party/googleapis/google/api/*.pb.go` were incompatible to recent `github.com/golang/protobuf`.
#71 will fix this issue.

**Comment by codefx9** [comment] 2015-12-10 01:21
Thank you @yugui for looking into this quickly. Please merge #71 into master.

**Comment by yugui** [comment] 2015-12-10 02:05
merged.

**Comment by codefx9** [comment] 2015-12-10 03:51
Thanks @yugui . Everything is working here. For someone checking this issue, the fix was:

 * Update grpc-gateway (go get -u ...)
 * Update protoc build command to include the correct path for google/api
```
--go_out=Mgoogle/api/annotations.proto=github.com/gengo/grpc-gateway/third_party/googleapis/google/api,plugins=grpc:.
```

**Comment by mtsgrd** [comment] 2015-12-10 10:12
Thanks @yugui, you're a star!

**Comment by pgracio** [comment] 2015-12-10 10:53
Thanks @yugui this works like a charm!

**Closed** 2016-01-05 03:18 UTC
